---
title: "HUP_CHOP Correlation"
author: "Amrom"
date: "2018-08-31"
output: workflowr::wflow_html
---

## Introduction


```{r, echo=FALSE, warning=FALSE, message=FALSE}
libloc<-"~/icsh_irf/library"
library(knitr)
opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
               echo=FALSE, warning=FALSE, message=FALSE)
library(purrr,lib.loc=libloc)
library(tidyr,lib.loc=libloc)
library(stringr,lib.loc=libloc)
library(ggplot2,lib.loc=libloc)
library(dplyr,lib.loc=libloc)
library(here,lib.loc=libloc)
library(janitor,lib.loc=libloc)
library(mcr,lib.loc=libloc)
library(readxl,lib.loc=libloc)
library(cowplot,lib.loc=libloc)



```


```{r}
load(here("prepped_data","hup.Rdata"))
load(here("prepped_data","chop.Rdata"))

```

```{r}
matchup<-read_xlsx(here("data","sample matchup.xlsx"))
```


```{r}
matchup <- matchup %>% 
  mutate(date = format(date, "%m-%d-%Y")) %>% 
  mutate(chop_id = paste0(date,"__",sys_id))

chop <- chop %>% 
  mutate(chop_id = paste0(date,"__",sample_no)) %>% 
  mutate(chop_id = str_replace_all(chop_id,"/","-"))

colnames(chop)[3:5] <- paste0(colnames(chop)[3:5],"_chop")
colnames(hup)[3:5] <- paste0(colnames(hup)[3:5],"_hup")

df<-matchup %>% 
  left_join(chop, by="chop_id") %>% 
  left_join(hup,by=c("dxh_id" = "Sample")) %>% 
  mutate(IRF_hup = 100*IRF_hup)

df %>% 
  select(date.x,starts_with("ret"),starts_with("irf")) %>% 
  DT::datatable(colnames = c("Date","RET% XN","RET XN","RET% DxH","RET DxH","IRF XN","IRF DxH"))
```



```{r}

p1<-ggplot(df,aes(irf_percent_chop,IRF_hup))+
  geom_point()+
  geom_smooth()+
  labs(x="IRF Sysmex XN",y="IRF BC DxH")


p2<-ggplot(df,aes(irf_percent_chop,IRF_hup))+
  geom_point()+
  geom_smooth()+
  scale_x_log10()+
  labs(x="IRF Sysmex XN (log axis)",y="IRF BC DxH")



myp<-plot_grid(p1,p2,labels = "AUTO")
myp2<-add_sub(myp, "A. Plot represents correlation of IRF between DxH and XN.\nB. Correlation plotting XN data on log scale", x = 0, hjust = 0)
ggdraw(myp2)
  
```


```{r, results='markup'}

pbreg<-mcreg(log10(df$irf_percent_chop),(df$IRF_hup), method.reg = "Deming",na.rm = TRUE)
# 
# b0<-pbreg@glob.coef[1]
# b1<-pbreg@glob.coef[2]
# 
# 
# ggplot(df,aes(irf_percent_chop,IRF_hup))+
#   geom_point()+
#   geom_abline(slope = b1,intercept = b0)+
#   reg.conf.intervals(df$irf_percent_chop,df$IRF_hup,pbreg)
#   scale_x_log10()+
#   labs(x="IRF Sysmex XN (log scale)",y="IRF BC DxH")
# 


plot(pbreg,  x.lab = "Log Sysmex XN", y.lab = "BC DxH")

# sctest(log10(df$irf_percent_chop)~df$IRF_hup)

```


